server:
  port: 0

spring:
  application:
    name: pedidos-ms
  datasource:
    url: jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}